INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Không tuân thủ quy định về sử dụng còi xe');
INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Lỗi vi phạm tín hiệu giao thông');
INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Vi phạm quy định về nồng độ cồn');
INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Lỗi vượt quá tốc độ quy định');
INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Lỗi đi sai làn đường');
INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Sử dụng phương tiện không đảm bảo an toàn');
INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Lỗi không thắt dây an toàn');
INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Vi phạm quy định về giấy tờ xe');
INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Lỗi về độ tuổi của người tham gia điều khiển phương tiện');
INSERT IGNORE INTO LoiViPham (NoiDung) VALUES ('Không tuân thủ quy định về dừng và đỗ xe');
INSERT IGNORE INTO PhuongTien (TenPhuongTien) VALUES ('xe máy');
INSERT IGNORE INTO PhuongTien (TenPhuongTien) VALUES ('xe đạp, xe đạp máy, xe đạp điện');
INSERT IGNORE INTO PhuongTien (TenPhuongTien) VALUES ('máy kéo, xe máy chuyên dùng');
INSERT IGNORE INTO PhuongTien (TenPhuongTien) VALUES ('người đi bộ');
INSERT IGNORE INTO PhuongTien (TenPhuongTien) VALUES ('xe mô tô, gắn máy');
INSERT IGNORE INTO PhuongTien (TenPhuongTien) VALUES ('ô tô');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('bị tước quyền sử dụng giấy phép lái xe (khi điều khiển máy kéo), chứng chỉ bồi dưỡng kiến thức pháp luật về giao thông đường bộ (khi điều khiển xe máy chuyên dùng) từ 01 tháng đến 03 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe từ 01 tháng đến 03 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('1.000.000 đồng đến 2.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('3.000.000 đồng đến 5.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe từ 02 tháng đến 04 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('80.000 đồng đến 100.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước giấy phép lái xe từ 2-4 tháng nếu gây tai nạn');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe từ 01 đến 03 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('200.000 đồng đến 400.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe (khi điều khiển máy kéo), chứng chỉ bồi dưỡng kiến thức pháp luật về giao thông đường bộ (khi điều khiển xe máy chuyên dùng) từ 01 tháng đến 03 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tịch thu giấy phép lái xe không do cơ quan có thẩm quyền cấp, giấy phép lái xe bị tẩy xóa');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('30 triệu đồng đến 40 triệu đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('20.000.000 đến 100.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('2.000.000 đồng đến 3.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('100.000 đồng đến 200.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('bị tước quyền sử dụng giấy phép lái xe (khi điều khiển máy kéo),  chứng chỉ bồi dưỡng kiến thức pháp luật về giao thông đường bộ (khi điều khiển xe máy chuyên dùng) từ 02 tháng đến 04 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('4.000.000 đồng đến 6.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('60.000 đồng đến 80.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước giấy phép lái xe từ 16 tháng đến 18 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe từ 02 đến 04 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước giấy phép lái xe từ 22 tháng đến 24 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('phạt cảnh cáo');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('10.000.000 đồng đến 12.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước giấy phép lái xe từ 10 tháng đến 12 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('16.000.000 đồng đến 18.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tịch thu giấy chứng nhận, tem kiểm định an toàn kỹ thuật và bảo vệ môi trường, giấy đăng ký xe; bị tước quyền sử dụng giấy phép lái xe từ 01 tháng đến 03 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('6 triệu đồng đến 8 triệu đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('phạt tù từ 02 năm đến 07 năm');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe (khi điều khiển máy kéo), chứng chỉ bồi dưỡng kiến thức pháp luật về giao thông đường bộ (khi điều khiển xe máy chuyên dùng) từ 02 tháng đến 04 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe từ 2 - 4 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('300.000 đồng đến 400.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe (khi điều khiển máy kéo), chứng chỉ bồi dưỡng kiến thức pháp luật về giao thông đường bộ (khi điều khiển xe máy chuyên dùng) từ 10 tháng đến 12 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe (khi điều khiển máy kéo), chứng chỉ bồi dưỡng kiến thức pháp luật về giao thông đường bộ (khi điều khiển xe máy chuyên dùng) từ 16 tháng đến 18 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('6.000.000 đồng đến 8.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe hoặc chứng chỉ bồi dưỡng kiến thức pháp luật về giao thông đường bộ (khi điều khiển xe máy chuyên dùng) từ 01 tháng đến 03 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tước quyền sử dụng giấy phép lái xe (khi điều khiển máy kéo), chứng chỉ bồi dưỡng kiến thức pháp luật về giao thông đường bộ (khi điều khiển xe máy chuyên dùng) từ 22 tháng đến 24 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('bị tước quyền sử dụng giấy phép lái xe từ 02 đến 04 tháng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('800.000 đồng đến 1.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('phạt tù từ 05 năm đến 10 năm');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('30.000.000 đồng đến 40.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('800.000 đồng  đến 4.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('4.000.000 đồng đến 5.000.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('phạt cải tạo không giam giữ đến 03 năm hoặc phạt tù từ 06 tháng đến 03 năm');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('400.000 đồng đến 600.000 đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('16 triệu đồng đến 18 triệu đồng');
INSERT IGNORE INTO HinhPhat (NoiDung) VALUES ('tịch thu phương tiện');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không thắt dây an toàn khi điều khiển xe chạy trên đường');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Hành vi giao xe mô tô, xe gắn máy và các loại xe tương tự xe mô tô hoặc để cho người không đủ điều kiện, bao gồm cả trường hợp người điều khiển phương tiện có Giấy phép lái xe nhưng đã hết hạn sử dụng hoặc đang trong thời gian bị tước quyền sử dụng');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe trên đường cao tốc không đúng nơi quy định;  Không có báo hiệu để người lái xe khác biết khi buộc phải dừng xe, đỗ xe trên đường cao tốc không đúng nơi quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng/đỗ xe trên dải phân cách cố định giữa 2 đường xe chạy');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Chở người trên xe ô tô không thắt dây an toàn (tại vị trí có trang bị dây an toàn) khi xe đang chạy');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng/đỗ xe không tuân thủ quy định tại nơi đường bộ giao nhau với đường sắt hoặc trong phạm vi an toàn đường sắt');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe ở lòng đường đô thị trái quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Đỗ xe trên đường xe điện, đường xe buýt, miệng cống, miệng hầm của đường điện thoại, điện cao thế hoặc nơi dành cho xe chữa cháy lấy nước');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe không sát theo lề đường, hè phố phía bên phải theo chiều đi hoặc bánh xe gần nhất cách lề đường, hè phố quá 0.25  m');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Khi dừng xe, đỗ xe không có tín hiệu báo cho người điều khiển phương tiện khác biết');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe tại nơi có biển “Cấm dừng xe và đỗ xe”');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe trên phần đường xe chạy ở đoạn đường ngoài đô thị nơi có lề đường');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Gây thương tích hoặc gây tổn hại cho sức khỏe của 01 người mà tỷ lệ tổn thương cơ thể 61% trở lên');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Người từ đủ 16 tuổi đến dưới 18 tuổi điều khiển xe mô tô có dung tích xi lanh từ 50 cm3 trở lên');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Điều khiển phương tiện không có Giấy đăng ký xe theo quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe ở  trên đoạn đường cong hoặc gần đầu dốc nơi tầm nhìn bị che khuất; trên cầu, gầm cầu vượt, song song với một xe khác đang dừng, đỗ');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Đỗ xe nơi có biển cấm “Cấm đỗ xe” hoặc biển “Cấm dừng xe và đỗ xe”');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe trên đường xe điện, đường dành riêng cho xe buýt, trên miệng cống thoát nước, miệng hầm của đường điện thoại, điện cao thế,');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe không đúng quy định gây tai nạn giao thông');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng/đỗ không sát mép đường bên phải ở nơi đường hẹp hoặc không có lề đường');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Nồng độ cồn vượt quá 50 miligam đến 80 miligam/100 mililít máu hoặc vượt quá 0,25 miligam đến 0,4 miligam/1 lít khí thở');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không có Giấy phép lái xe (mô tô hai bánh có dung tích xi lanh dưới 175 cm3)');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe,đỗ xe không có tín hiệu báo cho người điều khiển phương tiện khác biết');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Gây thương tích hoặc gây tổn hại cho sức khỏe của 02 người trở lên mà tổng tỷ lệ tổn thương cơ thể của những người này từ 61% đến 121%');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('10-20km/h');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng/đỗ xe trên phần đường dành cho người đi bộ');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Người từ đủ 14 tuổi đến dưới 16 tuổi điều khiển xe mô tô, xe gắn máy (kể cả xe máy điện) và các loại xe tương tự xe mô tô hoặc điều khiển xe ô tô, máy kéo và các loại xe tương tự xe ô tô');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe ở lòng đường đô thị gây cản trở giao thông');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe trên đường xe điện, đường dành riêng cho xe buýt');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Đỗ xe chiếm phần đường xe chạy không đặt báo hiệu nguy hiểm, trừ trường hợp được phép');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Điều khiển phương tiện không có Giấy đăng ký xe theo quy định hoặc sử dụng Giấy đăng ký xe đã hết hạn');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Đỗ, để xe ở hè phố trái quy định của pháp luật');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Gây tai nạn');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Sử dụng Giấy đăng ký xe, Giấy chứng nhận, tem kiểm định an toàn kỹ thuật và bảo vệ môi trường không do cơ quan có thẩm quyền cấp hoặc bị tẩy xóa mà không chứng minh được nguồn gốc xuất xứ của phương tiện (không có giấy tờ, chứng từ chuyển quyền sở hữu xe hoặc giấy tờ, chứng từ nguồn gốc xe hợp pháp)');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Gây thương tích hoặc gây tổn hại cho sức khỏe của 03 người trở lên mà tổng tỷ lệ tổn thương cơ thể của những người này 201% trở lên');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe ngược với chiều lưu thông của làn đường; dừng xe, đỗ xe trên dải phân cách cố định ở giữa hai phần đường xe chạy');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Nồng độ cồn chưa vượt quá 50 miligam/100 mililít máu hoặc chưa vượt quá 0,25 miligam/1 lít khí thở');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe không đúng nơi trong hầm đường bộ không đúng nơi quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe/đỗ xe trên phần đường xe chạy ở đoạn ngoài đô thị nơi có lề đường rộng');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Đỗ xe không sát lề đường/hè phố phía bên phải theo chiều đi hoặc bánh xe gần nhất cách lề đường, hè phố quá 0.25m');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Bấm còi liên tục; bấm còi hơi trong đô thị, khu đông dân cư, trừ các xe ưu tiên đang đi làm nhiệm vụ theo quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Trên 20km/h');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe trên cầu, gầm cầu vượt, song song với xe khác đang dừng, dỗ');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Gây thiệt hại về tài sản từ 500.000.000 đồng đến dưới 1.500.000.000 đồng');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Nồng độ cồn nhưng chưa vượt quá 50 miligam/100 mililít máu hoặc chưa vượt quá 0,25 miligam/1 lít khí thở');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng/đỗ xe tại nơi đường bộ giao nhau, hoặc trong phạm vi 5m từ mép đường giao nhau');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe bên trái đường một chiều  hoặc bên trái (theo hướng lưu thông) của đường đôi, đoạn đường cong, đầu dốc che khuất tầm nhìn');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Gây thương tích hoặc gây tổn hại cho sức khỏe của 02 người trở lên mà tổng tỷ lệ tổn thương cơ thể của những người này từ 122% đến 200%;');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Khi đỗ xe chiếm một phần đường xe chạy không đặt ngay báo hiệu nguy hiểm theo quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không tuân thủ các quy định về dừng xe, đỗ xe tại nơi đường bộ giao nhau cùng mức với đường sắt');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không chấp hành yêu cầu kiểm tra về nồng độ cồn của người thi hành công vụ');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Đỗ xe tại nơi có biển “Cấm đỗ xe” hoặc biển “Cấm dừng xe và đỗ xe”');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không mang theo Giấy phép lái xe');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Làm chết 02 người');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Bấm còi, rú ga liên tục; bấm còi hơi, sử dụng đèn chiếu xa trong đô thị, khu đông dân cư, trừ các xe ưu tiên đang đi làm nhiệm vụ theo quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Giấy phép lái xe nhưng không phù hợp với loại xe đang điều khiển hoặc có Giấy phép lái xe nhưng đã hết hạn sử dụng từ 03 tháng trở lên');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe trên cầu');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng/đỗ xe ngược chiều lưu thông của làn đường');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Bấm còi trong thời gian từ 22 giờ ngày hôm trước đến 05 giờ ngày hôm sau trong đô thị, khu đông dân cư, trừ các xe ưu tiên đang đi làm nhiệm vụ theo quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Bấm còi, rú ga (nẹt pô) liên tục trong đô thị, khu đông dân cư, trừ các xe ưu tiên đang đi làm nhiệm vụ theo quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Đỗ xe nơi có biển “Cấm đỗ xe” hoặc biển “Cấm dừng xe và đỗ xe”');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Làm chết 03 người trở lên');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không có hoặc không mang Giấy chứng nhận bảo hiểm trách nhiệm dân sự');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Bấm còi trong đô thị và khu đông dân cư trong thời gian từ 22 giờ ngày hôm trước đến 05 giờ ngày hôm sau, trừ các xe ưu tiên đang đi làm nhiệm vụ theo quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe sai quy định gây tai nạn giao thông');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không có Giấy phép lái xe hoặc sử dụng Giấy phép lái xe không hợp lệ (không do cơ quan có thẩm quyền cấp hoặc đã bị tẩy xóa)');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng/đỗ xe không đúng quy định tại nơi giao nhau cùng mức với đường sắt hoặc trong phạm vi an toàn đường sắt');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe nơi có biển “Cấm dừng xe và đỗ xe”');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe ở bên trái đường một chiều hoặc bên trái (theo hướng lưu thông) của đường đôi;');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Làm chết 1 người');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng/đỗ xe tại điểm dừng đón, trả khách của xe buýt; trước cổng hoặc trong phạm vi 05 m hai bên cổng trụ sở cơ quan');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe trên đường xe điện, điểm dừng đón trả khách của xe buýt, nơi đường bộ giao nhau, trên phần đường dành cho người đi bộ qua đường');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe đỗ xe tại nơi đường bộ giao nhau cùng mức với đường sắt hoặc trong phạm vi an toàn của đường sắt');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không mang theo Giấy đăng ký xe');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe không đúng vị trí quy định ở những đoạn đường đã có bố trí nơi dừng xe, đỗ xe');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe trái quy định gây ùn tắc giao thông');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Bấm còi tại nơi có biển báo cấm sử dụng còi');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Nồng độ cồn vượt quá 80 miligam/100 mililít máu hoặc vượt quá 0,4 miligam/1 lít khí thở');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không có Giấy phép lái xe hoặc sử dụng Giấy phép lái xe không do cơ quan có thẩm quyền cấp hoặc  Giấy phép lái xe đã bị tẩy xóa');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe trong hầm đường bộ không đúng nơi quy định');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe không đúng nơi quy định trên đường cao tốc');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe không sát mép đường phía bên phải theo chiều đi ở nơi đường có lề đường hẹp hoặc không có lề đường');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Dừng xe, đỗ xe trên phần đường xe chạy ở đoạn đường ngoài đô thị nơi có lề đường rộng');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('20-35km/h');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Sử dụng Giấy đăng ký xe, Giấy chứng nhận, tem kiểm định an toàn kỹ thuật và bảo vệ môi trường không do cơ quan có thẩm quyền cấp hoặc bị tẩy xóa');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Lỗi không có hoặc không mang Giấy chứng nhận bảo hiểm trách nhiệm dân sự (giấy còn hiệu lực)');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('5-10km/h');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Trên 35km/h');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Gây thiệt hại về tài sản từ 100.000.000 đồng đến dưới 500.000.000 đồng');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Để xe ở lòng đường đô thị, hè phố trái quy định của pháp luật; đỗ xe ở lòng đường đô thị gây cản trở giao thông, đỗ xe trên đường xe điện, đỗ xe trên cầu gây cản trở giao thông');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Không có Giấy phép lái xe (xe mô tô hai bánh có dung tích xi lanh từ 175 cm3 trở lên)');
INSERT IGNORE INTO ChiTietLoi (NoiDung) VALUES ('Gây thiệt hại về tài sản 1.500.000.000 đồng trở lên');
